### ISSUE TITLE
Current version pinning prevents version bump to dbt_utils 0.9.x

### ISSUE THREAD

**Issue by daveworth** [Snowflake-Labs/dbt_constraints#21]
Hello!

In attempting to bump my local project to the newest `0.9.x` revisions of `dbt_utils` I found that our dependency on `dbt_constraints` prevented that upgrade due to pinning to a maximum of `0.8.x` of that same package.  After reviewing the changes to `dbt_utils` as well as the use of that package in this package I believe it is safe to relax the existing constraints to use the `0.9.x` train.  I was able to validate that change for Postgres in #20 but do not have access to Snowflake or other databases this may affect.

**Comment by sfc-gh-dflippo** [comment]
This is actually a mistake. I haven't actually used dbt_utils in many versions but forgot to clean up the packages.yml. I will delete the packages.yml entirely.
