### ISSUE TITLE
package doesn't create FK on Snapshots

### ISSUE THREAD

**Issue by DiegoWeichafe** [Snowflake-Labs/dbt_constraints#26]
For some reason if I add a FK on a snapshot table, this produces no effect.

![image](https://user-images.githubusercontent.com/30992331/191646581-eb941a96-3a77-4fe3-b5b2-4741641bdce6.png)

![image](https://user-images.githubusercontent.com/30992331/191646482-78c9c558-bea0-49f6-868f-7c3199438965.png)

**Comment by sfc-gh-dflippo** [comment]
The latest code in the main branch has the necessary fix and I am about to create a release after I update some of the documentation.

**Comment by sfc-gh-dflippo** [comment]
Thanks for identifying the problem and letting me know. A fix was submitted a couple weeks ago but I only got around to deploying the new release today.
