### ISSUE TITLE
Not Null constraints should be created first

### ISSUE THREAD

**Issue by ataft** [Snowflake-Labs/dbt_constraints#29]
It appears that the Not Null constraints are done last: 
https://github.com/Snowflake-Labs/dbt_constraints/blob/main/macros/create_constraints.sql#L146

Some databases (SQL Server at least) do not allow ALTER COLUMN on a column that another constraint (PK, UK, FK) is dependent on. You'll get an error like "The object 'SOME_TABLE_SOME_COLUMN_UK' is dependent on column 'SOME_COLUMN'".

Additionally, some databases will not allow Primary Keys on a Nullable column.

Does it make sense to have Not Null done first?

**Comment by sfc-gh-dflippo** [comment]
Actually, if there is a PK, I do the not null before the PK. I see your point though. It wouldn't be hard to move it up overall.

**Comment by sfc-gh-dflippo** [comment]
I made the change but now you have me wondering if these will fail the second time on an incremental or snapshot. I'm not checking if the column is already not null so it will try to issue the alter and that might not be allowed. Something you can test on Redshift?

**Comment by sfc-gh-dflippo** [comment]
To test, you just need to try to set a column as not null if it is already not null and has a PK on it. You don't need to try it in dbt.

**Comment by ataft** [comment]
Redshift does not allow ALTER COLUMN. My recent Redshift PR logs 'unsupported' when NOT NULL constraint is attempted.

In other databases, you can always issue ALTER COLUMN and set to NOT NULL regardless of the current state of the column. For posterity, I've just tested on Postgres and SQL Server.

**Comment by sfc-gh-dflippo** [comment]
So, is SQL server the only DB this change would benefit? I don't have support for it right now but had considered to at some point.

**Comment by sfc-gh-dflippo** [comment]
Originally I was going to test if the columns were already not null and even wrote the Snowflake code to do it. But then I tested and it was actually a little faster to just issue the alter since Snowflake would skip the operation at the cloud service layer. On SQL Server it might be better to test if it is not null before issuing the unnecessary alter. Moving not null constraints to run first seems fine in all DB.

**Comment by ataft** [comment]
Agreed, it should be first. SQL Server will not allow it unless it's first. Redshift will not allow you to create a primary key on a column unless it is NOT NULL, so if I'm able to fix that issue later on, then NOT NULL would need to be first as well. I tested Postgres, and it doesn't appear to care. Haven't tested MySQL, Oracle, BigQuery, etc., but wouldn't be surprised if they enforce similar rules as SQL Server and Redshift.

**Comment by sfc-gh-dflippo** [comment]
I know that Oracle implicitly makes a column not null when a PK is added. The only dependency it has is that your must have a PK or UK on the parent table for a FK.
