### ISSUE TITLE
Is this package still needed if `dbt >= 1.5.0` ?

### ISSUE THREAD

**Issue by romiof** [Snowflake-Labs/dbt_constraints#52]
Hello guys,

I'm starting my journey with dbt, to replace a old ETL (GUI) process which uses a database on-premise for destination.

My DW is a SQL Server, and I'm looking for the best way to implement PK / FK at my final models (_facts and dims in a star-schema_).

Then I reached at this nice package and at the same time, I also found that dbt 1.5 implements [Model Contracts](https://docs.getdbt.com/docs/collaborate/govern/model-contracts) and [Constraints Feature](https://docs.getdbt.com/reference/resource-properties/constraints).

So as far I understand, if my `dbt` is `>= 1.5.0` I can implement constraints without the need of this package.

Is that right or there is something that I'm missing? 

BR!

**Comment by ataft** [comment]
Well, sort of but not quite.

First, the [sqlserver](https://github.com/dbt-msft/dbt-sqlserver) adapter does not yet support dbt 1.5, so you'll need to wait for that package to both support 1.5 AND implement this new feature. However, sqlserver is not an official dbt adapter, so this could take a while.

Second, defining a primary_key constraints requires a contract. Requiring a contract then requires data_type to be set for each column. Requiring data_type to be set for each column makes dbt NOT database agnostic, which is something that I absolutely love about dbt. In short, to use the new PK/FK feature, you have to define data_type for every column. I commented on this in the following discussion: https://github.com/dbt-labs/dbt-core/discussions/6726. We'll see where that goes.

**Comment by sfc-gh-dflippo** [comment]
From my perspective, the best part of the dbt Constraints package is that it can be simply added to an existing project and it will automatically begin to create constraints based on tests. That is not the goal of the new contracts features. For those contracts, you have to explicitly define the constraints. This might seem a subtle difference but in practice it is fastly easier to enable dbt Constraints versus documenting all the additional contracts on top of tests you may already have. Additionally, although I have provided input to the dbt-Labs product team on their feature, at least initially, they don't support Snowflake's "RELY" attribute on constraints that powers our join elimination feature.

At this point, I intend to continue to support dbt Constraints.

**Comment by ataft** [comment]
@sfc-gh-dflippo  Great points. I'm wondering what your thoughts are and/or if you've discussed my points at all with the dbt Labs product team. I added [this discussion point](https://github.com/dbt-labs/dbt-core/discussions/6726#discussioncomment-6269541) to dbt-core, but no response.
