### ISSUE TITLE
Exclusion of a data catalog, database, or directory from a dbt_constraint build

### ISSUE THREAD

**Issue by dontpanicmorty** [Snowflake-Labs/dbt_constraints#61]
### Description
The [Please Note](https://github.com/Snowflake-Labs/dbt_constraints/tree/main#please-note) section of the dbt_constraints README.md explains that "When you add this package, dbt will automatically begin to create ... not null constraints for not_null tests." The [Disabling automatic constraint generation](https://github.com/Snowflake-Labs/dbt_constraints/tree/main#disabling-automatic-constraint-generation) subsection details how **not null constraints** can (only) be disabled for sources.

There is no functionality to disable constraint creation for other upstream model types like **snapshots**. Currently, my organization's dbt project has **not null** tests defined for most snapshots. Constraints should be created for production data through development with the option to enable and disable creating constraints for **raw/source** and **snapshot** data.

**Comment by sfc-gh-dflippo** [comment]
This was addressed with version 1.0.0
